/* eslint-disable @cspell/spellchecker */
import type { IconifyJSON } from '@iconify/types';

// Generated by scripts/sld/generate-symbol-assets.mjs
export const SLD_ICON_PACK = {
  prefix: 'sld',
  icons: {
    util: {
      body: '<circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="64" y1="48" x2="85" y2="48"/>\n<circle cx="40" cy="48" r="24"/>\n<path d="M24 50c4-8 8 8 12 0s8-8 12 0"/></g>',
      width: 96,
      height: 96,
    },
    gens: {
      body: '<circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="64" y1="48" x2="85" y2="48"/>\n<circle cx="40" cy="48" r="24"/>\n<circle cx="40" cy="48" r="9"/><line x1="40" y1="39" x2="40" y2="57"/><line x1="31" y1="48" x2="49" y2="48"/><path d="M24 48h7M49 48h7"/></g>',
      width: 96,
      height: 96,
    },
    pvin: {
      body: '<circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="64" y1="48" x2="85" y2="48"/>\n<circle cx="40" cy="48" r="24"/>\n<rect x="24" y="38" width="24" height="16" rx="2"/><line x1="32" y1="38" x2="32" y2="54"/><line x1="40" y1="38" x2="40" y2="54"/><line x1="24" y1="46" x2="48" y2="46"/><circle cx="54" cy="34" r="5"/><line x1="54" y1="25" x2="54" y2="22"/><line x1="61" y1="34" x2="64" y2="34"/></g>',
      width: 96,
      height: 96,
    },
    bess: {
      body: '<circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="64" y1="48" x2="85" y2="48"/>\n<circle cx="40" cy="48" r="24"/>\n<rect x="23" y="41" width="28" height="14" rx="2"/><line x1="51" y1="45" x2="54" y2="45"/><line x1="31" y1="45" x2="37" y2="45"/><line x1="34" y1="42" x2="34" y2="48"/><line x1="40" y1="51" x2="46" y2="51"/></g>',
      width: 96,
      height: 96,
    },
    turb: {
      body: '<circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="64" y1="48" x2="85" y2="48"/>\n<circle cx="40" cy="48" r="24"/>\n<circle cx="40" cy="48" r="3"/><line x1="40" y1="48" x2="40" y2="29"/><line x1="40" y1="48" x2="24" y2="57"/><line x1="40" y1="48" x2="56" y2="57"/><path d="M40 29l3 6h-6zM24 57l7-1-3-5zM56 57l-7-1 3-5z"/></g>',
      width: 96,
      height: 96,
    },
    buss: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="86" y2="48" stroke-width="5.6"/>\n<line x1="40" y1="37" x2="40" y2="59"/>\n<line x1="56" y1="37" x2="56" y2="59"/>\n<path d="M22 30h10M64 30h10M22 66h10M64 66h10"/></g>',
      width: 96,
      height: 96,
    },
    swgr: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="86" y2="48" stroke-width="5.6"/>\n<line x1="40" y1="37" x2="40" y2="59"/>\n<line x1="56" y1="37" x2="56" y2="59"/>\n<rect x="24" y="22" width="40" height="16" rx="2"/><line x1="34" y1="22" x2="34" y2="38"/><line x1="44" y1="22" x2="44" y2="38"/><line x1="54" y1="22" x2="54" y2="38"/></g>',
      width: 96,
      height: 96,
    },
    swbd: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="86" y2="48" stroke-width="5.6"/>\n<line x1="40" y1="37" x2="40" y2="59"/>\n<line x1="56" y1="37" x2="56" y2="59"/>\n<rect x="24" y="22" width="40" height="16" rx="2"/><line x1="36" y1="22" x2="36" y2="38"/><line x1="50" y1="22" x2="50" y2="38"/><path d="M28 30h32"/></g>',
      width: 96,
      height: 96,
    },
    pnlb: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="86" y2="48" stroke-width="5.6"/>\n<line x1="40" y1="37" x2="40" y2="59"/>\n<line x1="56" y1="37" x2="56" y2="59"/>\n<rect x="26" y="22" width="30" height="16" rx="2"/><line x1="31" y1="38" x2="31" y2="44"/><line x1="41" y1="38" x2="41" y2="44"/><line x1="51" y1="38" x2="51" y2="44"/></g>',
      width: 96,
      height: 96,
    },
    mccb: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="86" y2="48" stroke-width="5.6"/>\n<line x1="40" y1="37" x2="40" y2="59"/>\n<line x1="56" y1="37" x2="56" y2="59"/>\n<rect x="24" y="22" width="40" height="16" rx="2"/><circle cx="44" cy="30" r="5"/><path d="M41 33v-6l3 3 3-3v6"/></g>',
      width: 96,
      height: 96,
    },
    pdub: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="86" y2="48" stroke-width="5.6"/>\n<line x1="40" y1="37" x2="40" y2="59"/>\n<line x1="56" y1="37" x2="56" y2="59"/>\n<rect x="24" y="22" width="40" height="20" rx="2"/><circle cx="32" cy="28" r="1.4"/><circle cx="40" cy="28" r="1.4"/><circle cx="48" cy="28" r="1.4"/><circle cx="56" cy="28" r="1.4"/><line x1="28" y1="36" x2="60" y2="36"/></g>',
      width: 96,
      height: 96,
    },
    rppb: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="86" y2="48" stroke-width="5.6"/>\n<line x1="40" y1="37" x2="40" y2="59"/>\n<line x1="56" y1="37" x2="56" y2="59"/>\n<rect x="26" y="20" width="28" height="18" rx="2"/><line x1="30" y1="26" x2="50" y2="26"/><line x1="30" y1="32" x2="50" y2="32"/><path d="M54 29h10" stroke-dasharray="3 3"/></g>',
      width: 96,
      height: 96,
    },
    busw: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="86" y2="48" stroke-width="5.6"/>\n<line x1="40" y1="37" x2="40" y2="59"/>\n<line x1="56" y1="37" x2="56" y2="59"/>\n<rect x="20" y="40" width="44" height="16" rx="2"/><line x1="26" y1="40" x2="26" y2="56"/><line x1="34" y1="40" x2="34" y2="56"/><line x1="42" y1="40" x2="42" y2="56"/><line x1="50" y1="40" x2="50" y2="56"/></g>',
      width: 96,
      height: 96,
    },
    tapb: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="86" y2="48" stroke-width="5.6"/>\n<line x1="40" y1="37" x2="40" y2="59"/>\n<line x1="56" y1="37" x2="56" y2="59"/>\n<rect x="32" y="26" width="18" height="24" rx="2"/><line x1="41" y1="22" x2="41" y2="26"/><line x1="41" y1="50" x2="41" y2="56"/></g>',
      width: 96,
      height: 96,
    },
    parb: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="86" y2="48" stroke-width="5.6"/>\n<line x1="40" y1="37" x2="40" y2="59"/>\n<line x1="56" y1="37" x2="56" y2="59"/>\n<line x1="18" y1="42" x2="78" y2="42" stroke-width="5"/><line x1="18" y1="54" x2="78" y2="54" stroke-width="5"/><line x1="48" y1="42" x2="48" y2="54"/></g>',
      width: 96,
      height: 96,
    },
    mvbs: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="86" y2="48" stroke-width="5.6"/>\n<line x1="40" y1="37" x2="40" y2="59"/>\n<line x1="56" y1="37" x2="56" y2="59"/>\n<path d="M44 24l-8 14h8l-6 12 14-18h-8l6-8z"/><line x1="20" y1="30" x2="66" y2="30"/></g>',
      width: 96,
      height: 96,
    },
    mvsw: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="86" y2="48" stroke-width="5.6"/>\n<line x1="40" y1="37" x2="40" y2="59"/>\n<line x1="56" y1="37" x2="56" y2="59"/>\n<rect x="24" y="22" width="40" height="16" rx="2"/><path d="M44 22v16M34 22v16M54 22v16"/><path d="M44 42l-6 8h6l-4 8 10-12h-6l4-4z"/></g>',
      width: 96,
      height: 96,
    },
    rmub: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="86" y2="48" stroke-width="5.6"/>\n<line x1="40" y1="37" x2="40" y2="59"/>\n<line x1="56" y1="37" x2="56" y2="59"/>\n<circle cx="42" cy="48" r="14"/><circle cx="42" cy="34" r="2"/><circle cx="30" cy="54" r="2"/><circle cx="54" cy="54" r="2"/><line x1="56" y1="48" x2="72" y2="48"/></g>',
      width: 96,
      height: 96,
    },
    brkr: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<line x1="34" y1="34" x2="62" y2="62"/><line x1="34" y1="62" x2="62" y2="34"/></g>',
      width: 96,
      height: 96,
    },
    acbr: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<line x1="34" y1="34" x2="62" y2="62"/><path d="M42 58l6-16 6 16M44 52h8"/></g>',
      width: 96,
      height: 96,
    },
    vcbr: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<circle cx="40" cy="48" r="6"/><circle cx="56" cy="48" r="6"/><line x1="46" y1="48" x2="50" y2="48"/></g>',
      width: 96,
      height: 96,
    },
    lbsw: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<line x1="34" y1="58" x2="46" y2="48"/><line x1="46" y1="48" x2="62" y2="38"/><circle cx="34" cy="58" r="2"/><circle cx="62" cy="38" r="2"/></g>',
      width: 96,
      height: 96,
    },
    disc: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<line x1="34" y1="58" x2="58" y2="38"/><circle cx="34" cy="58" r="2"/><line x1="58" y1="38" x2="62" y2="38"/></g>',
      width: 96,
      height: 96,
    },
    fusd: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<path d="M34 48h6l4-6 6 12 6-12 6 12h0"/></g>',
      width: 96,
      height: 96,
    },
    swch: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<line x1="34" y1="48" x2="62" y2="48"/><circle cx="34" cy="48" r="2"/><circle cx="62" cy="48" r="2"/></g>',
      width: 96,
      height: 96,
    },
    cont: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<line x1="34" y1="42" x2="42" y2="42"/><line x1="54" y1="42" x2="62" y2="42"/><line x1="34" y1="54" x2="42" y2="54"/><line x1="54" y1="54" x2="62" y2="54"/><circle cx="48" cy="48" r="5"/></g>',
      width: 96,
      height: 96,
    },
    trfm: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<path d="M34 54c2-6 4-6 6 0s4 6 6 0"/><path d="M50 54c2-6 4-6 6 0s4 6 6 0"/></g>',
      width: 96,
      height: 96,
    },
    auto: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<path d="M34 54c2-6 4-6 6 0s4 6 6 0"/><path d="M50 54c2-6 4-6 6 0s4 6 6 0"/><line x1="48" y1="34" x2="48" y2="43"/><path d="M46 41l2 2 2-2"/></g>',
      width: 96,
      height: 96,
    },
    rect: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<path d="M34 56l10-16 10 16z"/><line x1="54" y1="40" x2="62" y2="40"/><line x1="54" y1="56" x2="62" y2="56"/></g>',
      width: 96,
      height: 96,
    },
    invt: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<path d="M32 50c4-8 8 8 12 0s8-8 12 0"/></g>',
      width: 96,
      height: 96,
    },
    chrg: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<rect x="35" y="42" width="16" height="10" rx="1"/><line x1="51" y1="45" x2="54" y2="45"/><line x1="40" y1="45" x2="45" y2="45"/><line x1="42.5" y1="42.5" x2="42.5" y2="47.5"/><path d="M54 57l8-6-8-6"/></g>',
      width: 96,
      height: 96,
    },
    vfdr: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<path d="M32 56h5l3-10 3 10 3-10 3 10h5"/><path d="M32 38c4 0 8 4 12 4s8-4 12-4"/></g>',
      width: 96,
      height: 96,
    },
    soft: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<line x1="34" y1="58" x2="34" y2="38"/><line x1="34" y1="58" x2="62" y2="58"/><line x1="34" y1="58" x2="62" y2="38"/></g>',
      width: 96,
      height: 96,
    },
    reac: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<path d="M34 50c2-6 4-6 6 0s4 6 6 0 4-6 6 0 4 6 6 0"/></g>',
      width: 96,
      height: 96,
    },
    hflt: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<line x1="34" y1="40" x2="42" y2="40"/><line x1="42" y1="34" x2="42" y2="46"/><line x1="48" y1="34" x2="48" y2="46"/><line x1="48" y1="40" x2="62" y2="40"/><path d="M34 56h28"/></g>',
      width: 96,
      height: 96,
    },
    metr: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<circle cx="48" cy="48" r="10"/><path d="M43 53v-10l5 5 5-5v10"/></g>',
      width: 96,
      height: 96,
    },
    enrg: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<circle cx="48" cy="48" r="10"/><path d="M45 40l-3 8h5l-2 8 7-10h-5l2-6z"/></g>',
      width: 96,
      height: 96,
    },
    pqmt: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<circle cx="48" cy="48" r="10"/><path d="M40 48h4l2-4 2 8 2-4h6"/></g>',
      width: 96,
      height: 96,
    },
    ctxf: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<circle cx="48" cy="48" r="11"/><circle cx="48" cy="48" r="5"/></g>',
      width: 96,
      height: 96,
    },
    vtxf: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<path d="M36 56V40l12-6 12 6v16"/><line x1="48" y1="34" x2="48" y2="56"/></g>',
      width: 96,
      height: 96,
    },
    cabx: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<path d="M34 56c5-14 9 14 14 0s9-14 14 0"/><path d="M34 44c5 14 9-14 14 0s9 14 14 0"/></g>',
      width: 96,
      height: 96,
    },
    cond: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<circle cx="48" cy="48" r="12"/><circle cx="48" cy="48" r="6"/></g>',
      width: 96,
      height: 96,
    },
    tray: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<line x1="34" y1="40" x2="62" y2="40"/><line x1="34" y1="56" x2="62" y2="56"/><line x1="38" y1="40" x2="38" y2="56"/><line x1="44" y1="40" x2="44" y2="56"/><line x1="50" y1="40" x2="50" y2="56"/><line x1="56" y1="40" x2="56" y2="56"/></g>',
      width: 96,
      height: 96,
    },
    duct: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<circle cx="40" cy="44" r="4"/><circle cx="48" cy="44" r="4"/><circle cx="56" cy="44" r="4"/><circle cx="44" cy="52" r="4"/><circle cx="52" cy="52" r="4"/></g>',
      width: 96,
      height: 96,
    },
    wire: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<path d="M34 54c4-10 8 10 12 0s8-10 12 0"/><circle cx="34" cy="54" r="1.6"/><circle cx="58" cy="54" r="1.6"/></g>',
      width: 96,
      height: 96,
    },
    jbox: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="21" y2="48"/>\n<line x1="75" y1="48" x2="86" y2="48"/>\n<rect x="21" y="25" width="54" height="46" rx="5"/>\n<rect x="36" y="36" width="24" height="24" rx="2"/><line x1="40" y1="40" x2="56" y2="56"/><line x1="56" y1="40" x2="40" y2="56"/></g>',
      width: 96,
      height: 96,
    },
    load: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<rect x="28" y="32" width="40" height="32" rx="4"/><path d="M34 50h6l4-8 4 16 4-8h10"/></g>',
      width: 96,
      height: 96,
    },
    lght: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<circle cx="48" cy="45" r="12"/><path d="M44 58h8M45 62h6"/><path d="M42 45c2-3 4-3 6 0s4 3 6 0"/></g>',
      width: 96,
      height: 96,
    },
    rcpt: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<rect x="30" y="34" width="36" height="28" rx="5"/><line x1="42" y1="42" x2="42" y2="50"/><line x1="54" y1="42" x2="54" y2="50"/><circle cx="48" cy="56" r="2"/></g>',
      width: 96,
      height: 96,
    },
    motr: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<circle cx="48" cy="48" r="14"/><path d="M42 56V40l6 8 6-8v16"/></g>',
      width: 96,
      height: 96,
    },
    evch: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<rect x="34" y="34" width="22" height="26" rx="3"/><line x1="41" y1="36" x2="41" y2="31"/><line x1="49" y1="36" x2="49" y2="31"/><path d="M39 46h12M45 40v12"/></g>',
      width: 96,
      height: 96,
    },
    ahux: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<rect x="30" y="32" width="36" height="32" rx="4"/><circle cx="48" cy="48" r="8"/><path d="M48 40l4 8h-8zM40 52l8-4v8zM56 52l-8-4v8z"/></g>',
      width: 96,
      height: 96,
    },
    rtux: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<rect x="30" y="34" width="36" height="28" rx="4"/><line x1="34" y1="34" x2="62" y2="34"/><circle cx="48" cy="49" r="7"/><path d="M48 42l3 7h-6zM41 52l7-3v6zM55 52l-7-3v6z"/></g>',
      width: 96,
      height: 96,
    },
    chlr: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<rect x="30" y="32" width="36" height="32" rx="4"/><path d="M48 38v20M40 42l16 12M56 42L40 54"/><circle cx="48" cy="48" r="5"/></g>',
      width: 96,
      height: 96,
    },
    pump: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<circle cx="46" cy="48" r="12"/><path d="M46 42v12M40 48h12"/><path d="M58 48h10l-6 5z"/></g>',
      width: 96,
      height: 96,
    },
    fanx: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<circle cx="48" cy="48" r="13"/><path d="M48 48l0-10c4 0 7 3 7 7zM48 48l9 5c-2 3-6 5-10 3zM48 48l-9 5c-2-3-1-8 3-10z"/></g>',
      width: 96,
      height: 96,
    },
    fpmp: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<circle cx="42" cy="50" r="10"/><path d="M42 44v12M36 50h12"/><path d="M56 44c4 3 4 8 0 11-3-2-4-6-2-9 1-2 2-3 2-6 1 1 2 3 0 4z"/></g>',
      width: 96,
      height: 96,
    },
    elev: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<rect x="32" y="32" width="32" height="32" rx="4"/><path d="M40 50l8-10 8 10M40 46l8 10 8-10"/></g>',
      width: 96,
      height: 96,
    },
    escl: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<path d="M30 60h36l-8-8h-8l-8-8h-12"/><line x1="30" y1="60" x2="30" y2="48"/><line x1="66" y1="60" x2="66" y2="48"/></g>',
      width: 96,
      height: 96,
    },
    itld: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<rect x="34" y="30" width="28" height="36" rx="3"/><line x1="38" y1="38" x2="58" y2="38"/><line x1="38" y1="46" x2="58" y2="46"/><line x1="38" y1="54" x2="58" y2="54"/><circle cx="40" cy="61" r="1.5"/><circle cx="45" cy="61" r="1.5"/></g>',
      width: 96,
      height: 96,
    },
    tenl: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<rect x="32" y="30" width="34" height="36" rx="2"/><line x1="40" y1="36" x2="40" y2="60"/><line x1="48" y1="36" x2="48" y2="60"/><line x1="56" y1="36" x2="56" y2="60"/><line x1="32" y1="44" x2="66" y2="44"/><line x1="32" y1="52" x2="66" y2="52"/></g>',
      width: 96,
      height: 96,
    },
    spdv: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<path d="M48 34l-8 14h8l-6 12 14-18h-8l6-8z"/><path d="M48 60v6M44 66h8M45 69h6"/></g>',
      width: 96,
      height: 96,
    },
    capb: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<line x1="38" y1="38" x2="38" y2="60"/><line x1="52" y1="38" x2="52" y2="60"/><line x1="30" y1="49" x2="38" y2="49"/><line x1="52" y1="49" x2="64" y2="49"/></g>',
      width: 96,
      height: 96,
    },
    svgv: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<rect x="32" y="34" width="32" height="28" rx="3"/><path d="M36 48c3-6 6 6 9 0s6-6 9 0 6 6 9 0"/></g>',
      width: 96,
      height: 96,
    },
    svcv: {
      body: '<circle cx="8" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="48" x2="24" y2="48"/>\n<rect x="32" y="34" width="32" height="28" rx="3"/><path d="M36 56l8-14 8 14"/><line x1="52" y1="42" x2="60" y2="42"/><line x1="52" y1="56" x2="60" y2="56"/></g>',
      width: 96,
      height: 96,
    },
    atss: {
      body: '<circle cx="8" cy="34" r="2.15" fill="currentColor" stroke="none"/><circle cx="8" cy="62" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="34" x2="18" y2="34"/>\n<line x1="10" y1="62" x2="18" y2="62"/>\n<line x1="79" y1="48" x2="86" y2="48"/>\n<rect x="18" y="18" width="61" height="60" rx="8" stroke-dasharray="6 4"/>\n<rect x="30" y="30" width="16" height="10" rx="2"/><rect x="30" y="56" width="16" height="10" rx="2"/><line x1="46" y1="35" x2="58" y2="48"/><line x1="46" y1="61" x2="58" y2="48"/><circle cx="60" cy="48" r="4"/></g>',
      width: 96,
      height: 96,
    },
    stss: {
      body: '<circle cx="8" cy="34" r="2.15" fill="currentColor" stroke="none"/><circle cx="8" cy="62" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="34" x2="18" y2="34"/>\n<line x1="10" y1="62" x2="18" y2="62"/>\n<line x1="79" y1="48" x2="86" y2="48"/>\n<rect x="18" y="18" width="61" height="60" rx="8" stroke-dasharray="6 4"/>\n<path d="M30 34l10 0 6 8"/><path d="M30 62l10 0 6-8"/><path d="M52 42l8 6-8 6"/><path d="M60 42l8 6-8 6"/><line x1="68" y1="48" x2="74" y2="48"/></g>',
      width: 96,
      height: 96,
    },
    upss: {
      body: '<circle cx="8" cy="34" r="2.15" fill="currentColor" stroke="none"/><circle cx="8" cy="62" r="2.15" fill="currentColor" stroke="none"/><circle cx="88" cy="48" r="2.15" fill="currentColor" stroke="none"/><g fill="none" stroke="currentColor" stroke-width="2.4" stroke-linecap="round" stroke-linejoin="round">\n<line x1="10" y1="34" x2="18" y2="34"/>\n<line x1="10" y1="62" x2="18" y2="62"/>\n<line x1="79" y1="48" x2="86" y2="48"/>\n<rect x="18" y="18" width="61" height="60" rx="8" stroke-dasharray="6 4"/>\n<rect x="26" y="30" width="14" height="12" rx="2"/><rect x="26" y="54" width="14" height="12" rx="2"/><rect x="50" y="42" width="12" height="12" rx="2"/><line x1="40" y1="36" x2="50" y2="48"/><line x1="40" y1="60" x2="50" y2="48"/><line x1="62" y1="48" x2="74" y2="48"/></g>',
      width: 96,
      height: 96,
    },
  },
} as const satisfies IconifyJSON;
